use_frameworks!

platform :ios, '9.0'

target 'PLITextField_Example' do
  pod 'PLITextField', :path => '../'
  pod 'FlagPhoneNumber'

  target 'PLITextField_Tests' do
    inherit! :search_paths

    
  end
end
